# -*- coding: utf-8 -*-
"""Nidal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZjHU3jE3K4oUAiEzKMv6KjnfFAS10i6
"""

import numpy as np
import pandas as pd
np.random.seed(42)
n=500
distance=np.random.uniform(10,100,n)
fog=np.random.uniform(0,1,n)
dust=np.random.uniform(0,1,n)
power=np.random.uniform(1,10,n)
snr=(power*120)/(distance*(1+fog+dust))
ber=np.exp(-snr)
data=pd.DataFrame({
    "Distance":distance,
    "Fog":fog,
    "Dust":dust,
    "Power":power,
    "SNR":snr,
    "BER":ber,
})
data.head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
X=data[["Distance","Fog","Dust","Power"]]
y=data["BER"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model=RandomForestRegressor()
model.fit(X_train, y_train)
pred=model.predict(X_test)

from sklearn.metrics import mean_squared_error
print ("MSE:", mean_squared_error(y_test, pred))

import matplotlib.pyplot as plt
plt.plot(y_test.values[:50], label="Actual BER")
plt.plot(pred[:50], label="predicted BER")
plt.legend()
plt.show()

y_snr= data["SNR"]
X_train, X_test, y_train, y_test= train_test_split(X, y_snr, test_size=0.2)
model.fit(X_train, y_train)
pred_snr= model.predict(X_test)

from sklearn.metrics import mean_squared_error
print("SNR MSE:", mean_squared_error(y_test, pred_snr))

plt.plot(y_test.values[:50], label="Actual SNR")
plt.plot(pred_snr[:50], label="predicted SNR")
plt.legend()
plt.show()